// <auto-generated />
using System;
using Fiap.Web.RotaDaReciclagem.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.RotaDaReciclagem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240627010249_AddAgendamentos")]
    partial class AddAgendamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.AgendamentoModel", b =>
                {
                    b.Property<int>("AgendamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendamentoId"));

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE");

                    b.Property<int>("MoradorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantidadeLitros")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("AgendamentoId");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("MoradorId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.CaminhaoModel", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaminhaoId"));

                    b.Property<int>("CapacidadeLitros")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Motorista")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CaminhaoId");

                    b.ToTable("Caminhoes", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.MoradorModel", b =>
                {
                    b.Property<int>("MoradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoradorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EnderecoBairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EnderecoComplemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("EnderecoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.HasKey("MoradorId");

                    b.ToTable("Moradores", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.AgendamentoModel", b =>
                {
                    b.HasOne("Fiap.Web.RotaDaReciclagem.Models.CaminhaoModel", "Caminhao")
                        .WithMany("Agendamentos")
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Web.RotaDaReciclagem.Models.MoradorModel", "Morador")
                        .WithMany("Agendamentos")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.CaminhaoModel", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("Fiap.Web.RotaDaReciclagem.Models.MoradorModel", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
